# Generated by Django 3.2.5 on 2022-01-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customer_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='discount_used',
            field=models.BooleanField(default=False),
        ),
    ]
