# Generated by Django 3.2.5 on 2022-01-08 19:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customer_discount_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='code',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
