# Generated by Django 3.2.5 on 2022-01-08 19:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
