# Generated by Django 3.2.5 on 2022-01-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_testimony'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimony',
            options={'verbose_name_plural': 'Testimonies'},
        ),
        migrations.AddField(
            model_name='testimony',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
