# Generated by Django 3.2.5 on 2022-01-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20220115_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='image',
            field=models.ImageField(default='cat.jpg', upload_to='feedback_pics'),
        ),
    ]
