# Generated by Django 3.2.5 on 2022-01-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=33)),
                ('hour', models.CharField(choices=[('9H', '9H - 10H'), ('10H', '10H - 11H'), ('11H', '11H - 12H'), ('12H', '12H - 13H'), ('13H', '13H - 14H'), ('14H', '14H - 15H'), ('15H', '15H - 16H'), ('16H', '16H - 17H')], max_length=33)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('date', models.DateField()),
            ],
        ),
    ]
