# Generated by Django 3.2.5 on 2022-01-17 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_for_front_page',
        ),
    ]
