# Generated by Django 3.2.5 on 2022-04-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_reply_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='title',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
    ]
